version: "2"

networks:
  internal:
    driver: bridge
services:
  apache:
    container_name: "apache"
    image: "webdevops/apache"
    volumes:
      - "../dist:/app"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.local.rule=Host(`alvitre.com.br`,`www.alvitre.com.br`)"
      - "traefik.http.services.local.loadbalancer.server.port=80"
